; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=cahp -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=CAHP

define i16 @bare_select(i1 %a, i16 %b, i16 %c) {
; CAHP-LABEL: bare_select:
; CAHP:       # %bb.0:
; CHAP-NEXT:	andi	a3, a0, 1
; CHAP-NEXT:	lsi	a4, 0
; CHAP-NEXT:	mov	a0, a1
; CHAP-NEXT:	bne	a3, a4, .LBB0_2
; CHAP-NEXT:# %bb.1:
; CHAP-NEXT:	mov	a0, a2
; CHAP-NEXT:.LBB0_2:
; CHAP-NEXT:	jr	ra

  %1 = select i1 %a, i16 %b, i16 %c
  ret i16 %1
}
