; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=cahp -verify-machineinstrs -filetype=obj < %s \
; RUN:   -o /dev/null 2>&1
; RUN: llc -mtriple=cahp -verify-machineinstrs < %s | FileCheck %s

define void @relax_bcc(i1 %a) {
; CHECK-LABEL: relax_bcc:
; CHECK:       # %bb.0:
; CHECK-NEXT:	andi2	a0, 1
; CHECK-NEXT:	lsi	a1, 0
; CHECK-NEXT:	bne	a0, a1, .LBB0_1
; CHECK-NEXT:	js	.LBB0_2
; CHECK-NEXT:.LBB0_1:                                # %iftrue
; CHECK-NEXT:	#APP
; CHECK-NEXT:	.zero 512
; CHECK-NEXT:	#NO_APP
; CHECK-NEXT:.LBB0_2:                                # %tail
; CHECK-NEXT:	jr	ra
  br i1 %a, label %iftrue, label %tail

iftrue:
  call void asm sideeffect ".space 512", ""()
  br label %tail

tail:
  ret void
}
