; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=cahp -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=CAHP %s

declare i8* @llvm.frameaddress(i32)
declare i8* @llvm.returnaddress(i32)

define i8* @test_frameaddress_0() nounwind {
; CAHP-LABEL: test_frameaddress_0:
; CAHP:       # %bb.0:
; CAHP-NEXT:	addi2	sp, -4
; CAHP-NEXT:	swsp	ra, 2(sp)
; CAHP-NEXT:	swsp	fp, 0(sp)
; CAHP-NEXT:	addi	fp, sp, 4
; CAHP-NEXT:	mov	a0, fp
; CAHP-NEXT:	lwsp	fp, 0(sp)
; CAHP-NEXT:	lwsp	ra, 2(sp)
; CAHP-NEXT:	addi2	sp, 4
; CAHP-NEXT:	jr	ra

  %1 = call i8* @llvm.frameaddress(i32 0)
  ret i8* %1
}

define i8* @test_frameaddress_2() nounwind {
; CAHP-LABEL: test_frameaddress_2:
; CAHP:       # %bb.0:
; CAHP-NEXT:	addi2	sp, -4
; CAHP-NEXT:	swsp	ra, 2(sp)
; CAHP-NEXT:	swsp	fp, 0(sp)
; CAHP-NEXT:	addi	fp, sp, 4
; CAHP-NEXT:	lw	a0, -4(fp)
; CAHP-NEXT:	lw	a0, -4(a0)
; CAHP-NEXT:	lwsp	fp, 0(sp)
; CAHP-NEXT:	lwsp	ra, 2(sp)
; CAHP-NEXT:	addi2	sp, 4
; CAHP-NEXT:	jr	ra

  %1 = call i8* @llvm.frameaddress(i32 2)
  ret i8* %1
}

define i8* @test_returnaddress_0() nounwind {
; CAHP-LABEL: test_returnaddress_0:
; CAHP:       # %bb.0:
; CAHP-NEXT:	mov	a0, ra
; CAHP-NEXT:	jr	ra

  %1 = call i8* @llvm.returnaddress(i32 0)
  ret i8* %1
}

define i8* @test_returnaddress_2() nounwind {
; CAHP-LABEL: test_returnaddress_2:
; CAHP:       # %bb.0:
; CAHP-NEXT:	addi2	sp, -4
; CAHP-NEXT:	swsp	ra, 2(sp)
; CAHP-NEXT:	swsp	fp, 0(sp)
; CAHP-NEXT:	addi	fp, sp, 4
; CAHP-NEXT:	lw	a0, -4(fp)
; CAHP-NEXT:	lw	a0, -4(a0)
; CAHP-NEXT:	lw	a0, -2(a0)
; CAHP-NEXT:	lwsp	fp, 0(sp)
; CAHP-NEXT:	lwsp	ra, 2(sp)
; CAHP-NEXT:	addi2	sp, 4
; CAHP-NEXT:	jr	ra

  %1 = call i8* @llvm.returnaddress(i32 2)
  ret i8* %1
}
