; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=cahp -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=CAHP %s

%struct.key_t = type { i16, [16 x i8] }

; FIXME: prologue and epilogue insertion must be implemented to complete this
; test

define i16 @test() nounwind {
; CAHP-LABEL: test:
; CAHP:       # %bb.0:
; CAHP-NEXT:    addi2 sp, -22
; CAHP-NEXT:    swsp ra, 20(sp)
; CAHP-NEXT:    swsp s0, 18(sp)
; CAHP-NEXT:    lsi s0, 0
; CAHP-NEXT:    swsp s0, 8(sp)
; CAHP-NEXT:    swsp s0, 6(sp)
; CAHP-NEXT:    swsp s0, 4(sp)
; CAHP-NEXT:    swsp s0, 2(sp)
; CAHP-NEXT:    swsp s0, 0(sp)
; CAHP-NEXT:    addi a0, sp, 2
; CAHP-NEXT:    lui a1, %hi(test1)
; CAHP-NEXT:    addi a1, a1, %lo(test1)
; CAHP-NEXT:    jalr a1
; CAHP-NEXT:    mov a0, s0
; CAHP-NEXT:    lwsp s0, 18(sp)
; CAHP-NEXT:    lwsp ra, 20(sp)
; CAHP-NEXT:    addi2 sp, 22
; CAHP-NEXT:    jr ra

  %key = alloca %struct.key_t, align 2
  %1 = bitcast %struct.key_t* %key to i8*
  call void @llvm.memset.p0i8.i64(i8* %1, i8 0, i64 10, i32 2, i1 false)
  %2 = getelementptr inbounds %struct.key_t, %struct.key_t* %key, i64 0, i32 1, i64 0
  call void @test1(i8* %2)
  ret i16 0
}

declare void @llvm.memset.p0i8.i64(i8* nocapture, i8, i64, i32, i1)

declare void @test1(i8*)
