; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=cahp -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=CAHP

; TODO: check the generated instructions for the equivalent of seqz, snez,
; sltz, sgtz map to something simple

define i16 @icmp_eq(i16 %a, i16 %b) nounwind {
; CAHP-LABEL: icmp_eq:
; CAHP:       # %bb.0:
; CAHP-NEXT:	beq	a0, a1, .LBB0_1
; CAHP-NEXT:# %bb.2:
; CAHP-NEXT:	lsi	a0, 0
; CAHP-NEXT:	jr	ra
; CAHP-NEXT:.LBB0_1:
; CAHP-NEXT:	lsi	a0, 1
; CAHP-NEXT:	jr	ra

  %1 = icmp eq i16 %a, %b
  %2 = zext i1 %1 to i16
  ret i16 %2
}

define i16 @icmp_ne(i16 %a, i16 %b) nounwind {
; CAHP-LABEL: icmp_ne:
; CAHP:       # %bb.0:
; CAHP-NEXT:	bne	a0, a1, .LBB1_1
; CAHP-NEXT:# %bb.2:
; CAHP-NEXT:	lsi	a0, 0
; CAHP-NEXT:	jr	ra
; CAHP-NEXT:.LBB1_1:
; CAHP-NEXT:	lsi	a0, 1
; CAHP-NEXT:	jr	ra

  %1 = icmp ne i16 %a, %b
  %2 = zext i1 %1 to i16
  ret i16 %2
}

define i16 @icmp_ugt(i16 %a, i16 %b) nounwind {
; CAHP-LABEL: icmp_ugt:
; CAHP:       # %bb.0:
; CAHP-NEXT:	bltu	a1, a0, .LBB2_1
; CAHP-NEXT:# %bb.2:
; CAHP-NEXT:	lsi	a0, 0
; CAHP-NEXT:	jr	ra
; CAHP-NEXT:.LBB2_1:
; CAHP-NEXT:	lsi	a0, 1
; CAHP-NEXT:	jr	ra

  %1 = icmp ugt i16 %a, %b
  %2 = zext i1 %1 to i16
  ret i16 %2
}

define i16 @icmp_uge(i16 %a, i16 %b) nounwind {
; CAHP-LABEL: icmp_uge:
; CAHP:       # %bb.0:
; CAHP-NEXT:	bleu	a1, a0, .LBB3_1
; CAHP-NEXT:# %bb.2:
; CAHP-NEXT:	lsi	a0, 0
; CAHP-NEXT:	jr	ra
; CAHP-NEXT:.LBB3_1:
; CAHP-NEXT:	lsi	a0, 1
; CAHP-NEXT:	jr	ra

  %1 = icmp uge i16 %a, %b
  %2 = zext i1 %1 to i16
  ret i16 %2
}

define i16 @icmp_ult(i16 %a, i16 %b) nounwind {
; CAHP-LABEL: icmp_ult:
; CAHP:       # %bb.0:
; CAHP-NEXT:	bltu	a0, a1, .LBB4_1
; CAHP-NEXT:# %bb.2:
; CAHP-NEXT:	lsi	a0, 0
; CAHP-NEXT:	jr	ra
; CAHP-NEXT:.LBB4_1:
; CAHP-NEXT:	lsi	a0, 1
; CAHP-NEXT:	jr	ra

  %1 = icmp ult i16 %a, %b
  %2 = zext i1 %1 to i16
  ret i16 %2
}

define i16 @icmp_ule(i16 %a, i16 %b) nounwind {
; CAHP-LABEL: icmp_ule:
; CAHP:       # %bb.0:
; CAHP-NEXT:	bleu	a0, a1, .LBB5_1
; CAHP-NEXT:# %bb.2:
; CAHP-NEXT:	lsi	a0, 0
; CAHP-NEXT:	jr	ra
; CAHP-NEXT:.LBB5_1:
; CAHP-NEXT:	lsi	a0, 1
; CAHP-NEXT:	jr	ra

  %1 = icmp ule i16 %a, %b
  %2 = zext i1 %1 to i16
  ret i16 %2
}

define i16 @icmp_sgt(i16 %a, i16 %b) nounwind {
; CAHP-LABEL: icmp_sgt:
; CAHP:       # %bb.0:
; CAHP-NEXT:	blt	a1, a0, .LBB6_1
; CAHP-NEXT:# %bb.2:
; CAHP-NEXT:	lsi	a0, 0
; CAHP-NEXT:	jr	ra
; CAHP-NEXT:.LBB6_1:
; CAHP-NEXT:	lsi	a0, 1
; CAHP-NEXT:	jr	ra

  %1 = icmp sgt i16 %a, %b
  %2 = zext i1 %1 to i16
  ret i16 %2
}

define i16 @icmp_sge(i16 %a, i16 %b) nounwind {
; CAHP-LABEL: icmp_sge:
; CAHP:       # %bb.0:
; CAHP-NEXT:	ble	a1, a0, .LBB7_1
; CAHP-NEXT:# %bb.2:
; CAHP-NEXT:	lsi	a0, 0
; CAHP-NEXT:	jr	ra
; CAHP-NEXT:.LBB7_1:
; CAHP-NEXT:	lsi	a0, 1
; CAHP-NEXT:	jr	ra

  %1 = icmp sge i16 %a, %b
  %2 = zext i1 %1 to i16
  ret i16 %2
}

define i16 @icmp_slt(i16 %a, i16 %b) nounwind {
; CAHP-LABEL: icmp_slt:
; CAHP:       # %bb.0:
; CAHP-NEXT:	blt	a0, a1, .LBB8_1
; CAHP-NEXT:# %bb.2:
; CAHP-NEXT:	lsi	a0, 0
; CAHP-NEXT:	jr	ra
; CAHP-NEXT:.LBB8_1:
; CAHP-NEXT:	lsi	a0, 1
; CAHP-NEXT:	jr	ra

  %1 = icmp slt i16 %a, %b
  %2 = zext i1 %1 to i16
  ret i16 %2
}

define i16 @icmp_sle(i16 %a, i16 %b) nounwind {
; CAHP-LABEL: icmp_sle:
; CAHP:       # %bb.0:
; CAHP-NEXT:	ble	a0, a1, .LBB9_1
; CAHP-NEXT:# %bb.2:
; CAHP-NEXT:	lsi	a0, 0
; CAHP-NEXT:	jr	ra
; CAHP-NEXT:.LBB9_1:
; CAHP-NEXT:	lsi	a0, 1
; CAHP-NEXT:	jr	ra

  %1 = icmp sle i16 %a, %b
  %2 = zext i1 %1 to i16
  ret i16 %2
}

; TODO: check variants with an immediate?
