; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=cahp -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=CAHP

; Materializing constants

define i16 @zero() nounwind {
; CAHP-LABEL: zero:
; CAHP:       # %bb.0:
; CAHP-NEXT:    lsi a0, 0
; CAHP-NEXT:    jr ra
  ret i16 0
}

define i16 @pos_small1() nounwind {
; CAHP-LABEL: pos_small1:
; CAHP:       # %bb.0:
; CAHP-NEXT:    lsi a0, 31
; CAHP-NEXT:    jr ra
  ret i16 31
}

define i16 @neg_small1() nounwind {
; CAHP-LABEL: neg_small1:
; CAHP:       # %bb.0:
; CAHP-NEXT:    lsi a0, -32
; CAHP-NEXT:    jr ra
  ret i16 -32
}

define i16 @pos_small2() nounwind {
; CAHP-LABEL: pos_small2:
; CAHP:       # %bb.0:
; CAHP-NEXT:    li a0, 511
; CAHP-NEXT:    jr ra
  ret i16 511
}

define i16 @neg_small2() nounwind {
; CAHP-LABEL: neg_small2:
; CAHP:       # %bb.0:
; CAHP-NEXT:    li a0, -512
; CAHP-NEXT:    jr ra
  ret i16 -512
}

define i16 @pos_i16() nounwind {
; CAHP-LABEL: pos_i16:
; CAHP:       # %bb.0:
; CAHP-NEXT:    lui a0, 22
; CAHP-NEXT:    addi a0, a0, 457
; CAHP-NEXT:    jr ra
  ret i16 22985
}

define i16 @neg_i16() nounwind {
; CAHP-LABEL: neg_i16:
; CAHP:       # %bb.0:
; CAHP-NEXT:    lui a0, 42
; CAHP-NEXT:    addi a0, a0, -457
; CAHP-NEXT:    jr ra
  ret i16 -22985
}

define i16 @pos_i16_hi6_only() nounwind {
; CAHP-LABEL: pos_i16_hi6_only:
; CAHP:       # %bb.0:
; CAHP-NEXT:    lui a0, 16
; CAHP-NEXT:    jr ra
  ret i16 16384
}

define i16 @neg_i16_hi6_only() nounwind {
; CAHP-LABEL: neg_i16_hi6_only:
; CAHP:       # %bb.0:
; CAHP-NEXT:    lui a0, 32
; CAHP-NEXT:    jr ra
  ret i16 -32768
}
