; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=cahp -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=CAHP

define i16 @foo(i16 %a, i16 *%b) {
; CAHP-LABEL: foo:
; CAHP:       # %bb.0:
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	bne	a0, a2, .LBB0_1
; CAHP-NEXT:# %bb.2:
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	beq	a0, a2, .LBB0_3
; CAHP-NEXT:.LBB0_4:
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	bleu	a0, a2, .LBB0_5
; CAHP-NEXT:.LBB0_6:
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	bltu	a0, a2, .LBB0_7
; CAHP-NEXT:.LBB0_8:
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	bleu	a2, a0, .LBB0_9
; CAHP-NEXT:.LBB0_10:
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	bltu	a2, a0, .LBB0_11
; CAHP-NEXT:.LBB0_12:
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	ble	a0, a2, .LBB0_13
; CAHP-NEXT:.LBB0_14:
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	blt	a0, a2, .LBB0_15
; CAHP-NEXT:.LBB0_16:
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	ble	a2, a0, .LBB0_17
; CAHP-NEXT:.LBB0_18:
; CAHP-NEXT:	lw	a1, 0(a1)
; CAHP-NEXT:	blt	a1, a0, .LBB0_19
; CAHP-NEXT:.LBB0_20:
; CAHP-NEXT:	jr	ra
; CAHP-NEXT:.LBB0_1:
; CAHP-NEXT:	mov	a0, a2
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	bne	a0, a2, .LBB0_4
; CAHP-NEXT:.LBB0_3:
; CAHP-NEXT:	mov	a0, a2
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	bltu	a2, a0, .LBB0_6
; CAHP-NEXT:.LBB0_5:
; CAHP-NEXT:	mov	a0, a2
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	bleu	a2, a0, .LBB0_8
; CAHP-NEXT:.LBB0_7:
; CAHP-NEXT:	mov	a0, a2
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	bltu	a0, a2, .LBB0_10
; CAHP-NEXT:.LBB0_9:
; CAHP-NEXT:	mov	a0, a2
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	bleu	a0, a2, .LBB0_12
; CAHP-NEXT:.LBB0_11:
; CAHP-NEXT:	mov	a0, a2
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	blt	a2, a0, .LBB0_14
; CAHP-NEXT:.LBB0_13:
; CAHP-NEXT:	mov	a0, a2
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	ble	a2, a0, .LBB0_16
; CAHP-NEXT:.LBB0_15:
; CAHP-NEXT:	mov	a0, a2
; CAHP-NEXT:	lw	a2, 0(a1)
; CAHP-NEXT:	blt	a0, a2, .LBB0_18
; CAHP-NEXT:.LBB0_17:
; CAHP-NEXT:	mov	a0, a2
; CAHP-NEXT:	lw	a1, 0(a1)
; CAHP-NEXT:	ble	a0, a1, .LBB0_20
; CAHP-NEXT:.LBB0_19:
; CAHP-NEXT:	mov	a0, a1
; CAHP-NEXT:	jr	ra

  %val1 = load volatile i16, i16* %b
  %tst1 = icmp eq i16 %a, %val1
  %val2 = select i1 %tst1, i16 %a, i16 %val1

  %val3 = load volatile i16, i16* %b
  %tst2 = icmp ne i16 %val2, %val3
  %val4 = select i1 %tst2, i16 %val2, i16 %val3

  %val5 = load volatile i16, i16* %b
  %tst3 = icmp ugt i16 %val4, %val5
  %val6 = select i1 %tst3, i16 %val4, i16 %val5

  %val7 = load volatile i16, i16* %b
  %tst4 = icmp uge i16 %val6, %val7
  %val8 = select i1 %tst4, i16 %val6, i16 %val7

  %val9 = load volatile i16, i16* %b
  %tst5 = icmp ult i16 %val8, %val9
  %val10 = select i1 %tst5, i16 %val8, i16 %val9

  %val11 = load volatile i16, i16* %b
  %tst6 = icmp ule i16 %val10, %val11
  %val12 = select i1 %tst6, i16 %val10, i16 %val11

  %val13 = load volatile i16, i16* %b
  %tst7 = icmp sgt i16 %val12, %val13
  %val14 = select i1 %tst7, i16 %val12, i16 %val13

  %val15 = load volatile i16, i16* %b
  %tst8 = icmp sge i16 %val14, %val15
  %val16 = select i1 %tst8, i16 %val14, i16 %val15

  %val17 = load volatile i16, i16* %b
  %tst9 = icmp slt i16 %val16, %val17
  %val18 = select i1 %tst9, i16 %val16, i16 %val17

  %val19 = load volatile i16, i16* %b
  %tst10 = icmp sle i16 %val18, %val19
  %val20 = select i1 %tst10, i16 %val18, i16 %val19

  ret i16 %val20
}
