; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=cahp -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=CAHP

; Check load/store operations on values wider than what is natively supported

define i32 @load_i32(i32 *%a) nounwind {
; CAHP-LABEL: load_i32:
; CAHP:       # %bb.0:
; CAHP-NEXT:    lw a2, 0(a0)
; CAHP-NEXT:    lw a1, 2(a0)
; CAHP-NEXT:    mov a0, a2
; CAHP-NEXT:    jr ra
  %1 = load i32, i32* %a
  ret i32 %1
}
